version: 2.1　＃手順4の追加修正

jobs:
  run_cisco_7200:
    machine:
      enabled: true
    resource_class: iphonesekino-lab/eveng-resource
    steps:
      - checkout

      - run:
          name: Run Cisco 7200 Ansible Playbook
          command: |
            ansible-playbook playbooks/cisco-7200.yml

workflows:
  eveng_setup:
    jobs:
      - run_cisco_7200 #テスト→関野修正手順１→手順２→手順３→手順４
